version: '3.8'

services:
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./configs/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command: [
      '--config.file=/etc/prometheus/prometheus.yml',
      '--storage.tsdb.path=/prometheus'
    ]
    ports: ["9090:9090"]
    networks: [monitoring, myapp_default]

  grafana:
    image: grafana/grafana:latest
    volumes: 
      - grafana_data:/var/lib/grafana
    ports: ["3000:3000"]
    env_file: .env  # This line is crucial
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
    networks: [monitoring]

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    volumes: [
      "/:/rootfs:ro",
      "/var/run:/var/run:ro",
      "/sys:/sys:ro",
      "/var/lib/docker/:/var/lib/docker:ro"
    ]
    ports: ["8080:8080"]
    networks: [monitoring]

  node-exporter:
    image: prom/node-exporter:latest
    volumes: [
      "/proc:/host/proc:ro",
      "/sys:/host/sys:ro",
      "/:/rootfs:ro"
    ]
    command: [
      '--path.procfs=/host/proc',
      '--path.sysfs=/host/sys'
    ]
    ports: ["9100:9100"]
    networks: [monitoring]

networks:
  monitoring:
  myapp_default:
    external: true

volumes:
  prometheus_data:
  grafana_data: